#define GEO_SETUP_CELL ZCube4Cell
#define GEO_SETUP_RANK 1

#define GEO_SETUP_CELLS_CNT 128
#define GEO_SETUP_STEPS_CNT 128

#define GEO_SETUP_DSPACE 3.0
#define GEO_SETUP_DTIME 0.001

#define GEO_SETUP_BULK 1000.0
#define GEO_SETUP_RHO 0.001
